### ISSUE TITLE
two  questions about ExpertUtilizationDropout and  dimension of the MixtureOfExpertsLayer 

### ISSUE THREAD

**Issue by ningyuwhut** [AmazaspShumik/mtlearn#1]
Hi,I read the repo and have two questions that annoys me.
1. ExpertUtilizationDropout layer
in the comment  below
> Builds main component of the layer by creating dropout layer that has the same binary mask for each element in the batch."

I don't understand why the dropout layer has the same binary mask for each element in the batch, is that necessary?
2.dimension of the MixtureOfExpertsLayer 
in the implementation of MixtureOfExpertsLayer 
`# compute weighted output of experts `
`    moe_output = 0`
 `   for i, expert_output in enumerate(experts_output):`
 `     moe_output += (expert_output`
`                     *tf.expand_dims(expert_utilization_prob[:,i], axis=-1)`
 `                   )`
It seems that the output dimension of MixtureOfExpertsLayer is [N,1] and N is the batch size.

but in MultiGateMixtureOfExperts
` moe = [moe(inputs) for moe in self.moe_layers]`
`outputs = [task_layer(moe[i]) for i, task_layer in enumerate(self.task_layers)]`

so the output of MixtureOfExpertsLayer is the input of task_layer, but if the output of MixtureOfExpertsLayer  of each sample  in the batch is a scalar, so the input of the task_layer is also a scala, won't that hurt the performance of mmoe ?

Is it a bettor choice that the output of MixtureOfExpertsLayer is still a vector ?

Thanks.

**Comment by AmazaspShumik** [comment]
Hi sorry for such a late reply and thank you very much for questions/obervations

1) Yes that is the trick to make mixture of experts stable (picked it up in the paper by the same authors presented on Recsys 2019), one of the most  problematic issues in Mixture of Experts is collapsing, when most of the time only several of experts are utilized. So the same authors came up with regularization technique to prevent collapse by using dropout on the levels of the experts it is mentioned in this paper "Recommending what video to watch next: a multitask ranking system".

2) You are right that "so the output of MixtureOfExpertsLayer is the input of task_layer", however output of MixtureOfExpertsLayer is not [batch_size,1], if you look at code snippet that you pasted expert_output can be any dimensionality. You can define expert to be an MLP with last layer having 20 units for instance, in that case output of MOE layer will be weighted average of K matrices [N,20], where K is the number of experts.
